### ISSUE TITLE
Chuffed ignores alldifferent on unconstrained variables in FlatZinc

### ISSUE THREAD

**Issue by guidotack** [chuffed/chuffed#10]
On the attached FlatZinc model, chuffed ignores the alldifferent constraint.

[alldiff_chuffed.fzn.zip](https://github.com/chuffed/chuffed/files/1717799/alldiff_chuffed.fzn.zip)

**Comment by Dekker1** [comment]
This issue seems to be caused by the fact that Chuffed chooses to use `IntVarLL` for the representation of the decision variables (because of large domain), and uses the `AllDiffValue` propagator. This propagator relies on the `remVal` method to remove values, but this call is ignored when using `IntVarLL`.
A solution would be to either change the variable representation when required or use a propagator that reasons about the bounds instead of punching gaps when this representation is used.

**Comment by schutta** [comment]
Annotating the all-different constraint by ```::bounds``` works as intended. The easy solution for the issue would to check for the integer variable type and if one variable is ```IntVarLL``` then to use the ```AllDiffBounds``` propagator.

Note that the current default all_different propagator is the value propagator, which only removes values when a variable is fixed. This is a very cheap propagator, but won't propagate anything when variable bounds changes. We should think about to also make the ```AllDiffBounds``` propagator as a default one.
