### ISSUE TITLE
warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808

### ISSUE THREAD

**Issue by yurivict** [chuffed/chuffed#143]
```
/usr/ports/math/chuffed/work/chuffed-0.12.0/chuffed/primitives/linear.cpp:390:15: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
        if (limit >= INT64_MAX) {
                  ~~ ^~~~~~~~~
/usr/include/x86/_stdint.h:90:19: note: expanded from macro 'INT64_MAX'
#define INT64_MAX       0x7fffffffffffffff
                        ^~~~~~~~~~~~~~~~~~
1 warning generated.
```

Version: 0.12.0
clang-15
FreeBSD 13.2

**Comment by Dekker1** [comment]
With the usage of `INT64_MAX` this is does not cause any problem other than a warning during compilation. There are many (at least seemingly) correct narrowing conversions in Chuffed, which is why it was disabled in our [clang-tidy configuration](https://github.com/chuffed/chuffed/blob/develop/.clang-tidy#L5). At present time we do not have the manpower to investigate these.

I'm happy to review and accept pull request that fix these issues, but I will remove them from the issue tracker as the Chuffed team will at present time not work on them.
