### ISSUE TITLE
Chuffed returns `malloc(): Cannot allocate memory`

### ISSUE THREAD

**Issue by raphaelboudreault** [chuffed/chuffed#155]
Hi!
I'm trying to run Chuffed 0.12.1 on the attached flatzinc `test_fzn.fzn` (compiled with MiniZinc 2.7.6). I'm getting the `malloc(): Cannot allocate memory` error and the MiniZinc driver fails with the `ERROR` status, both on Windows 10 and Ubuntu 22.04. If I comment some of my constraints (`test_fzn_2.fzn`), I instead get the `Unsatisfiable` status, for which I identified the UNSAT constraints. If I instead comment only the UNSAT constraints (`test_fzn_3.fzn`), I successfully obtain solutions.

[test_fzn.zip](https://github.com/chuffed/chuffed/files/13272733/test_fzn.zip)

**Comment by Dekker1** [comment]
It seems that the problem doesn't immediately gives a trace, but I wonder whether the problem isn't as simple as that memory is a big issue.

The `test_fzn.fzn` file contains many integer variables (~100) with all the same high upper bound `64000`, that are not in the other `fzn` files. (I assume this means you are enabling and disabling in MiniZinc, not the FZN files). Since the number of literals is still (just) under the lazy threshold, Chuffed will try and actively allocate Boolean variables for each value (and in-equality). I think think is just not possible on most hardware.

**Comment by raphaelboudreault** [comment]
Thanks for the quick reply! Yes, I was indeed enabling/disabling in MiniZinc. Ah, that's probably it. I should try playing with the lazy integer variables setting then. Thanks!
