### ISSUE TITLE
Docs for C++ API

### ISSUE THREAD

**Issue by i-kudryavtsev** [chuffed/chuffed#158]
Hi Chuffed Team,

thanks for your great work on the Chuffed solver!

Do you have any documentation/description of Chuffed C++ API? I want to generate cp problems on the flight and solve them. Also, I’m interested in adding specific for my area global constraints. And, especially, efficient modeling bit fields of arbitrary length. 

My apologies if this is not an appropriate place to ask questions but I didn’t find any chuffed related forums/groups.

Best regards

**Comment by Dekker1** [comment]
I'm afraid there is very limited (only in-code) documentation on the Chuffed API or the Chuffed solver's internals. In general it might be worthwhile considering using Chuffed through MiniZinc rather than using it directly. Otherwise, make sure to have a good look at the different examples, maybe the FlatZinc parser, and feel free to ask more questions.

**Comment by i-kudryavtsev** [comment]
I see, thanks a lot! I will start with FlatZinc parser. 

I started with the MiniZinc and I already have a working solution, but some constraints I believe could be drastically improved with custom propagators.
