### ISSUE TITLE
Updating chuffed's copyright claims

### ISSUE THREAD

**Issue by kaol** [chuffed/chuffed#185]
Hi, Chuffed is pretty sparse on copyright attributions. The only mention I found was in the LICENSE file, "Copyright (c) 2015 geoffchu". Of course, there are many years of contributions after that. On the README file I see attributions listed as "Geoffrey Chu, Peter J. Stuckey, Andreas Schutt, Thorsten Ehlers, Graeme Gange, Kathryn Francis" and then "Data61, CSIRO, Australia" and "Department of Computing and Information Systems University of Melbourne, Australia". What's the relation to Chuffed's copyrights with these names? Is it being held by individuals or the university or some part of it? I'm not sure I'm seeing the names listed above among the git committers (other than Andreas Schutt).

This is something I can't tell from the source code or git history alone so I'd like someone who knows about this to clarify what the status is.

**Comment by schutta** [comment]
I am neither an expert in licensing, copyrights, nor a lawyer , but I can provide you a background on Chuffed. Geoffrey Chu developed Chuffed during his PhD time under the supervision of Peter J. Stuckey in the Department of Computing and Information Systems at The University of Melbourne starting in 2008 +/- one year. At the same time, he also was a NICTA student and NICTA was merged into Data61, CSIRO, Australia in 2016. In my understanding, the IP rights were hold by NICTA. In 2015, NICTA made the decision to make Chuffed open source under the MIT license. Before that time (2015), Thorsten Ehlers, Graeme Gange, Kathryn Francis, and myself (all under supervision of Peter J. Stuckey) have made significant contributions to Chuffed, which ended up in the open source version of Chuffed. Since Chuffed was developed in an internal subversion repository in NICTA, migrated to git, and then copied to github, there is no history of the work performed before the upload to github.

If you want to know the specific contribution of each person listed then it is the best to look at their publication lists. Better would be to keep an up date file of Chuffed related publications.

**Comment by kaol** [comment]
Thanks, that clarifies it. The purpose I'm asking is that I'm looking into getting Chuffed to Debian and they want accuracy to the copyright claims.

One more question, I see that https://github.com/chuffed/chuffed/commits?author=ddeunagomez has made some substantial contributions, who's the copyright holder for that? The commit message mention's "Diego's PhD" so is it the copyright held by him or who he made the PhD work for? I couldn't deduce or find Diego's full name from his github handle and neither which university/institution it would be subsequently.

**Comment by Dekker1** [comment]
This was work by Diego De Uña, who was a PhD student at the University of Melbourne under the supervision of Peter J. Stuckey, Graeme Gange and Peter Schachte. His thesis titled "Discrete Optimization over Graph Problems" can be found here: https://rest.neptune-prod.its.unimelb.edu.au/server/api/core/bitstreams/3459eb9a-2f3d-503e-a37e-45a9d0b323d3/content

**Comment by kaol** [comment]
Chuffed is now in Debian so I think it's fair to say that the information I got here was satisfactory. Few of us are copyright lawyers but we have to act as ones sometimes. Closing this now and thanks for the digging.
