### ISSUE TITLE
Bad optimal solution reported

### ISSUE THREAD

**Issue by Dekker1** [chuffed/chuffed#70]
I'm running the attached program for the MT10x10 job shop. CPLEX finds the optimal solution at 930, Chuffed stops at 954 and reports it as optimal. If you set the upper bound to 930 instead of 1000, Chuffed finds a solution with cost 930 and says it is optimal as well.

 ```
include "globals.mzn";
int:nrJobs=10;
int:nrRes=10;

set of int: J=1..nrJobs;
set of int: R=1..nrRes;

array[J,R] of int:taskUse = [|
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9|
	0, 2, 4, 9, 3, 1, 6, 5, 7, 8|
	1, 0, 3, 2, 8, 5, 7, 6, 9, 4|
	1, 2, 0, 4, 6, 8, 7, 3, 9, 5|
	2, 0, 1, 5, 3, 4, 8, 7, 9, 6|
	2, 1, 5, 3, 8, 9, 0, 6, 4, 7|
	1, 0, 3, 2, 6, 5, 9, 8, 7, 4|
	2, 0, 1, 5, 4, 6, 8, 9, 7, 3|
	0, 1, 3, 5, 2, 9, 6, 7, 4, 8|
	1, 0, 2, 6, 8, 9, 5, 3, 4, 7 |];
			
array[J,R] of int:taskDuration= [|
	29, 78,  9, 36, 49, 11, 62, 56, 44, 21|
	43, 90, 75, 11, 69, 28, 46, 46, 72, 30|
	91, 85, 39, 74, 90, 10, 12, 89, 45, 33|
	81, 95, 71, 99,  9, 52, 85, 98, 22, 43|
	14,  6, 22, 61, 26, 69, 21, 49, 72, 53|
	84,  2, 52, 95, 48, 72, 47, 65,  6, 25|
	46, 37, 61, 13, 32, 21, 32, 89, 30, 55|
	31, 86, 46, 74, 32, 88, 19, 48, 36, 79|
	76, 69, 76, 51, 85, 11, 40, 89, 26, 74|
	85, 13, 61,  7, 64, 76, 47, 52, 90, 45 |];
									

int:ub =1000;


array[J,R] of var 0..ub:start;
var 0..ub:objective;

constraint forall(j in J) 
   (objective >= start[j,nrRes]+taskDuration[j,nrRes]);
 constraint forall(j in J, r in 1..nrRes-1)
  (start[j,r+1] >= start[j,r]+taskDuration[j,r]);
  constraint forall (r in R)
    (cumulative([start[j,k]|j in J, k in R where taskUse[j,k]+1=r],
                            [taskDuration[j,k]|j in J, k in R where taskUse[j,k]+1=r],
                            [1|j in J, k in R where taskUse[j,k]+1=r],1)
    );
   
  solve minimize objective;
```

Originally filed in the MiniZinc repository: https://github.com/MiniZinc/libminizinc/issues/460

**Comment by Samclou** [comment]
By inspecting the FlatZinc file associated with the model you gave [Issue70.txt](https://github.com/chuffed/chuffed/files/8941323/Issue70.txt), it appears from line 215 that the chuffed Disjunctive constraint is used. By running this FlatZinc file on a fzn-chuffed executable compiled in debug mode, we get the following error : `Assertion failed: (lb > sat.c_info[var(p)].val), function explain, file disjunctive.cpp, line 117.` The cause of this assertion fail is the type of the old_est member of the DisjunctiveBP class from file chuffed/chuffed/globals/disjunctive.cpp. This member is an array of Tchar, which causes an overflow whenever the minimum value of the starting time of a task is over 127 (which happens with this model).

Changing the Tchar types from the declaration of old_est (line 31) and its memory allocation (line 42) to Tint fixes this overflow issue.

The reason Minizinc did not fail due to the assertion of line 117 is that standard assertions have no effect in code compiled in Release mode. If this assertion is important to the validity of the minimisation search, maybe it could be changed from `assert` to `rassert`, so that it may still verify the validity of the clauses created.
