### ISSUE TITLE
Chuffed outputs no solution when using timeout

### ISSUE THREAD

**Issue by gablin** [chuffed/chuffed#85]
When I run chuffed with a timeout (-t flag) such that it does find a solution but is unable to prove optimality, it output no solution at all. I know that chuffed does find something if I include the -a flag - it's just that when only using -t it output nothing.

Is this intended behavior? Gecode does not behave this way (it outputs the best solution found).

**Comment by Dekker1** [comment]
Gecode's behaviour is at least intended from the MiniZinc solver standard. I think contributions to fix this would be very welcome.

**Comment by gablin** [comment]
After a bit of investigation, this turns out not to be a problem of chuffed itself, but minizinc when invoking chuffed. I tried running fzn-chuffed standalone, and then there are no problems with not outputting a solution when using timeout. Moreover, minizinc does not actually pass the '-t' flag to fzn-chuffed when using timeout (meaning minizinc must control this on its own).

**Comment by raphaelboudreault** [comment]
Note that this bug has also been referred in #54.

@Dekker1 While I thought that MR #87 and #88 would solve this issue, it still happens on Ubuntu 20.04.3 using MiniZinc 2.5.5. The flag `-t` is now passed correctly to Chuffed, but it seems like MiniZinc still kills Chuffed before it has the time to print anything. This can be seen using the flag `-s`, where Chuffed doesn't print any of its statistics when the timeout kicks in (when I'm pretty sure back in the days, it was doing so). Note that this behavior of missing output also happens when using Ctrl+C (only 'Interrupted' will be printed), whereas on master (0.10.4) the statistics have time to be printed.
